config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :contacts
  get "cities", to: "cities#index"

  # Defines the root path route ("/")
  root "contacts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :city
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = Country.find(params[:contact_country_id]).cities.order(:name)
    @target_id = params[:target_id]

    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cities/index.turbo_stream.erb
<%= turbo_stream.update @target_id do %>
  <%= options_from_collection_for_select @cities, :id, :name %>
<% end %>

app/views/contacts/_form.html.erb
<%= form_with model: contact do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>

  <div data-controller="dynamic-select"
       data-dynamic-select-url-value="<%= cities_path %>">

    <p>
      <%= f.label :country_id, 'Country' %>
      <%= f.collection_select :country_id, Country.order(:name), :id, :name,
              { prompt: 'Select Country' },
              { data: { action: "change->dynamic-select#change" } } %>
    </p>

    <p>
      <%= f.label :city_id, 'City' %>
      <%= f.collection_select :city_id, [], :id, :name, {},
              { data: { dynamic_select_target: "select" } } %>
    </p>
  </div>
<% end %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<%= link_to "New Contact", new_contact_path, class: "button" %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DynamicLinkedSelectFields</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>